### ISSUE TITLE
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 2 passed to TYPO3\CMS\Form\Service\TranslationService::translateFormElementError() 

### ISSUE THREAD

**Issue by Xippo** [evoWeb/recaptcha#11]
Got this error:
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 2 passed to TYPO3\CMS\Form\Service\TranslationService::translateFormElementError() must be of the type integer, float given, called in /html/typo3/typo3_src-8.7.8/typo3/sysext/form/Classes/ViewHelpers/TranslateElementErrorViewHelper.php on line 72 | TypeError thrown in file /html/typo3/typo3_src-8.7.8/typo3/sysext/form/Classes/Service/TranslationService.php in line 389. Requested URL: http://www.panther-packaging.de.tgm-server.de/kontakt/kontaktformular.html?tx_form_formframework%5Baction%5D=perform&tx_form_formframework%5Bcontroller%5D=FormFrontend&cHash=b6566333e11f2f256eeed9905fc9aeda `
System:
TYPO3 8.7.8
PHP  7.1.9

**Comment by garbast** [comment]
Sorry but 32bit is not and will not get supported.

**Comment by Xippo** [comment]
Hi thx for the quick answer.
I don't know if the Server is on 32bit and a swap to 64bit will solve the problem but what i know is that your error code is to big compared to the core codes.
You can see in the pull request that the only thing that i want, is that you use a error code like it does the rest of the TYPO3 core. A regular php timestamp, otherwise you will get this kind of error. And if this happen your extension can't be used on many hosters also big ones. Like the described system, it runs on an Managed Server XL from Mittwald. My 2 cents.

I wish you a great day

**Comment by garbast** [comment]
Changed the error number to the current timestamp. By the way the extension worked on Mittwald event without the change. The error number was a valid 64bit number and you dont get errors because of the high integer value but because 32bit systems treat them as float values.

**Comment by Xippo** [comment]
Thx for doing so. I understand the problem and probably could ask Mittwald to swap the Managed Server to 64bit architecture and the problem would be resolved, but the case shows that there are Mittwald managed servers(also not the cheapest one), like the mentioned one where it dosen't work, so there will be on other hosters too. So i think that the change is good for the stability of the extension, so thank you again for doing this small change. I wish you a good and sunny weekend

**Comment by Ich5003** [comment]
I have the same error 
`Argument 2 passed to TYPO3\CMS\Form\Service\TranslationService::translateFormElementError() must be of the type integer, float given, called in /.../typo3cms/typo3_src-8.7.12/typo3/sysext/form/Classes/ViewHelpers/TranslateElementErrorViewHelper.php on line 72 `

Is there any workaround to make this work?
Hosting provider is jweiland.net

**Comment by Ich5003** [comment]
Using the latest development branch worked.
Thank you
