### ISSUE TITLE
Server errors cause empty error messages and TYPO3 exceptions

### ISSUE THREAD

**Issue by pkerling** [evoWeb/recaptcha#14]
In the validator, the `error` response parameter is used for formatting the error message: https://github.com/evoWeb/recaptcha/blob/a101b748a2efb4223292ca018338b5676749d18e/Classes/Validation/RecaptchaValidator.php#L49

But for errors from the server, `error` is an array and not a string: https://github.com/evoWeb/recaptcha/blob/a101b748a2efb4223292ca018338b5676749d18e/Classes/Services/CaptchaService.php#L207

So the error message will not be found and TYPO3 (8.7) even throws an exception when displaying the form.

**Comment by garbast** [comment]
Ok i see the problem. Made a change in commit b8b71de. Please check the develop branch if this works for you so i could prepare a release.
