### ISSUE TITLE
Support Typo3 7 is broken

### ISSUE THREAD

**Issue by Domtaholic** [evoWeb/recaptcha#20]
This line: use TYPO3\CMS\Core\TypoScript\TypoScriptService; in the Service breaks in Typo3 7.

The class in Typo3 7 is located here: 

TYPO3\CMS\Extbase\Service\TypoScriptService.

**Comment by garbast** [comment]
Which version of the extension are you using?

**Comment by Domtaholic** [comment]
I Installed the latest one - but now i´m on 7.2.

But i guess i´m doing it wrong in that Version. I just included the Viewhelper - in 7.6, is this the common way implementing the recaptcha in default mailform?

Damn you´re fast :D

**Comment by garbast** [comment]
The latest version of recaptcha ist 8.7 and 9.x only. 

The last version compatible to 7.6 is version 7.2.1.

Only supported usage for 7.6 is the inclusion in ext:form. I dont know if this covers the mailform content element too.

**Comment by Domtaholic** [comment]
Hmm okay - nah probably not. 

I will get another extension then - thanks for fast response
