### ISSUE TITLE
Question belong to the lang integration

### ISSUE THREAD

**Issue by ayacoo** [evoWeb/recaptcha#22]
Hi!

we study https://developers.google.com/recaptcha/docs/display and see there is a doc for the language codes which will be add as parameter to the the url. E.g. _https://www.google.com/recaptcha/api.js?hl?fr_

It seems like the constant "lang" would not be used. We override the constant "api_server" and all is fine. Is this the right way? 

Option A (easy): Remove "lang" constant and documentate the url behavior
Option B: (medium): Combine "api_server" and "lang" if "lang" is given.

Thanks for your feedback!

**Comment by garbast** [comment]
You are right i will include the lang const next release

**Comment by garbast** [comment]
?hl= is now included but needs more testing because it seems as if its present even if the constant is empty

**Comment by garbast** [comment]
The behaviour is fixed in the latest version. There the ?hl= key is appended to the api.js inclusion.
