### ISSUE TITLE
Question belong 8.3 and lang in data-sitekey

### ISSUE THREAD

**Issue by ayacoo** [evoWeb/recaptcha#24]
Context: https://github.com/evoWeb/recaptcha/commit/c46c3689a51e9567663d6d48f39b587f02f5d540

Hi!

I see that you add the hl param to the data-sitekey attribute. Is this documented? If we use 8.3 we got "invalid key" messages. If we use the old way (8.2.8) we have no problems. Maybe you can explain the commit?

Thanks :-)

**Comment by garbast** [comment]
Well the code is pretty clear. If the constant plugin.tx_recaptcha.lang is set it will be appended with ?hl={$plugin.tx_recaptcha.lang}.
Only point where this could be a problem is the ? in the wrap. If you are using the typoscript output you can try and change it to & 
If you do not need to enforce the language it should be sufficient to just leave the constant an empty string.
