### ISSUE TITLE
ReCAPTCHA couldn't find user-provided function: onRecaptchaSubmit

### ISSUE THREAD

**Issue by matin73** [evoWeb/recaptcha#30]
Invisible reCaptcha not working on TYPO3 9.5

**Comment by garbast** [comment]
You need to include the static TypoScript and must not to empty the page object afterwards with page >

**Comment by garbast** [comment]
https://github.com/evoWeb/recaptcha/blob/1bbc24b9ae80df0d4de3a32c545b943040492443/Configuration/TypoScript/setup.typoscript#L85
