### ISSUE TITLE
file_get_contents Fehlermeldung wenn abgemeldet 

### ISSUE THREAD

**Issue by DaveWoody** [evoWeb/recaptcha#31]
Hallo! Habe heute mal das Plugin installiert sowie konfiguriert - hat auch alles super geklappt. Das einzige Problem was ich habe ist, wenn ich mich abmelde / bzw der Endnutzer besucht die Seite, dann bekomme ich eine file_get_contents Fehlermeldung

TYPO3-Version	8.7.30
	PHP-Version	7.1.33

Wenn ich eingeloggt bin funktioniert die Seite einwandfrei.

`#1476107295: PHP Warning: file_get_contents(/***/htdocs/relaunch/webroot/https://www.google.com/recaptcha/api.js): failed to open stream: No such file or directory in ***/htdocs/relaunch/webroot/typo3_src/typo3_src-8.7.30/typo3/sysext/core/Classes/Resource/ResourceCompressor.php line 411 (More information)`

**Comment by garbast** [comment]
The Extension does not use file_get_contents at all. But from what i read in your error message you include the remote api.js file as local resource, maybe with cached assets. That can not work but is nothing the extension causes.

**Comment by DaveWoody** [comment]
Found the problem. Posting here if anyone else is having this issue. 

This was / is a compression problem through typo3. It tries to compress the google.com/recaptcha/api.js  which does not work. Try to disable the compression for this url / file
