### ISSUE TITLE
Multiple forms on single page

### ISSUE THREAD

**Issue by DaveWoody** [evoWeb/recaptcha#32]
Hey i am having multiple forms on a single page and when i try to send one to see if the validation goes through, it  does not show the missing fields on the right form. Something i need to keep in mind for multiple forms on one page?

**Comment by garbast** [comment]
Sorry but this not an unsupported usage. The extension is garantied to work only with single forms on a page.

**Comment by Nano1237** [comment]
> Sorry but this not an unsupported usage.

So ... is it an unsupported usage or not? I think you meant "Sorry but this ~not~ an unsupported usage.". Or does it work with multiple forms on a single page?

**Comment by garbast** [comment]
Yeah sorry for the jibberish. This does not work and cant work, because recaptcha is based on sessions value, which would override each other.
