### ISSUE TITLE
Finishers won't be called if invisible recaptcha is used

### ISSUE THREAD

**Issue by PhpDevGuy** [evoWeb/recaptcha#33]
Same problem as mentioned in #7 but in different versions.

`TYPO3 9.5.14
EXT: form 9.5.14
EXT: recaptcha 9.1.3`

My setup / configuration seems to be correct since everything works as expected if a visible captcha is used.

I would appreciate your feedback.
Thanks in advance.

**Comment by garbast** [comment]
Please provide the .form.yaml file, so i can check it in my installation.

**Comment by PhpDevGuy** [comment]
Sure.
Here is an example setup:

**captchaTest.form.yaml**
`
renderingOptions:
  submitButtonLabel: Submit
  useInvisibleRecaptcha: true
type: Form
identifier: captchaTest
label: CaptchaTest
prototypeName: standard
finishers:
  -
    options:
      message: 'Lorem ipsum'
      contentElementUid: ''
    identifier: Confirmation
renderables:
  -
    renderingOptions:
      previousButtonLabel: 'Previous step'
      nextButtonLabel: 'Neue Seite'
    type: Page
    identifier: page-1
    label: Step
    renderables:
      -
        defaultValue: ''
        type: Text
        identifier: text-1
        label: Text
      -
        renderingOptions:
          submitButtonLabel: true
        type: Recaptcha
        identifier: recaptcha-1
        label: reCAPTCHA
        validators:
          -
            identifier: Recaptcha
`

The confirmation finisher is only used as an example here.
Other finishers also won't be called.

This exact form was tested and the problem still occurs,

**Comment by garbast** [comment]
Took me some time to set up a test environment and it worked as expected. I assume that you did not configured you installation. In special the last part is explicitly explained in the documentation. Why didnt your read it? https://docs.typo3.org/p/evoweb/recaptcha/9.1/en-us/Tutorial/Index.html

In general you always need the key in the constants:
plugin.tx_recaptcha.public_key = 6LfAH-UUAAAAAG09z2IO0myU_OQfmxKZYvONazdy
plugin.tx_recaptcha.private_key = 6LfAH-UUAAAAAIBscbFPlkURjDjinbOrHWjwHY3E

And for invisible recaptch you need these constants:
plugin.tx_recaptcha.include_invisible_recaptcha_callback = 1
plugin.tx_recaptcha.invisible_recaptcha_formname = captchaTest
