### ISSUE TITLE
JS loaded on all pages?

### ISSUE THREAD

**Issue by star26bsd** [evoWeb/recaptcha#34]
Hi - I have a quick question.

I have implemented your t3 extension successfully on my contact form. ReCaptcha works as expected. However, I see the according JS now loaded on all my pages, not just the contact form. Is that to be expected?

Typo3 9.5.14, ReCaptcha Extension 9.1.3

Thanks

**Comment by garbast** [comment]
Yes its intended.
It is an example integration with page.jsInline.1508480348393. If you dont want to have it on all pages, its up to you as an integrator to only have it present when you needed.
