### ISSUE TITLE
Include External JS

### ISSUE THREAD

**Issue by snits35m** [evoWeb/recaptcha#35]
Since the Javascript for Recaptcha is integrated from an external source (Google Server), the corresponding property should also be set so that the compression of JS files can be activated globally on the page.

The corresponding line should therefore be added to "setup.typoscript":
page.includeJSFooterlibs.recaptcha.external = 1

**Comment by garbast** [comment]
Integrated with commit b8f9df7

**Comment by antonfries** [comment]
Could you merge this commit into branch 9.x.x, so we don't have to overwrite this in custom typoscript?

**Comment by garbast** [comment]
If this saves you time, consider becoming a sponsor.
