### ISSUE TITLE
Not working if adding extension later

### ISSUE THREAD

**Issue by matin73** [evoWeb/recaptcha#36]
Recaptcha extension is not working, if you add/active it after spammer has already spamed form. There is a "required" per default missing if adding recaptcha field.

so spammer can still use old post parameters and emails are sent because there is no required validation

**Comment by garbast** [comment]
Feel free to send in a PR that fixes this problem.

**Comment by matin73** [comment]
https://forge.typo3.org/issues/91441#change-425704

**Comment by garbast** [comment]
Please test the develop branch. If this fixes your problem, i release a new version.

**Comment by matin73** [comment]
sorry - can not test it, because I changed other things, so spammer are not able to send mails at the moment
