### ISSUE TITLE
Language always english

### ISSUE THREAD

**Issue by TildBJ** [evoWeb/recaptcha#38]
When I change the value of plugin.recaptcha.lang to 'de' in the Extension Configuration it doesn't has an effect to the frontend. It always shows english labels. I cleared all the caches. This is my implementation in forms:

`      
-
        validators:
          -
            identifier: Recaptcha
        renderingOptions:
          submitButtonLabel: false
        type: Recaptcha
        identifier: recaptcha-1
        label: ''
`

I'm using TYPO3 9.5.20 and recaptcha 9.1.3

**Comment by garbast** [comment]
In general the language is based on the browser settings and auto detected. You should check what's  the url is, that includes the recaptcha javascript. It should have ?hl=de appended. So the constant should contain plugin.recaptcha.lang = ?hl=de
