### ISSUE TITLE
Error creating new form with recaptcha

### ISSUE THREAD

**Issue by rawk7000** [evoWeb/recaptcha#39]
TYPO3: 10.4.6
Recaptcha: 10.0.2
PHP: 7.3

I think I found a bug.

Creating a new form with a recaptcha creates the following error:
 #1297759968 TYPO3\CMS\Extbase\Property\Exception
Exception while property mapping at property path "": No hmac found for property "identifier" (form element "recaptcha-1" / "validators.NotEmpty") #1528591585

After saving, the form is created but without the recaptcha.

But: It still works to edit forms that already exist (with recaptcha). So its just with new forms.

**Comment by mvoehringer** [comment]
I can confirm the same error with the latest TYPO3  10.4.8 and Recaptcha 10.0.2 ... Recaptcha 10.0.0 don't have the problem

**Comment by pkarny** [comment]
Any update on this issue?

**Comment by mpr92** [comment]
I have the same problem in the latest TYPO3 10.4.9. Can someone help please?

**Comment by it-crow** [comment]
Same here, also with typo3 10.4.9. Need help, too...

**Comment by neusitelich** [comment]
I can confirm this problem in Typo3 10.4.9

**Comment by pstranghoener** [comment]
I can confirm it allthough. TYPO3 10.4.9
