### ISSUE TITLE
Some issues with docs at docs.typo3.org

### ISSUE THREAD

**Issue by DanielSiepmann** [evoWeb/recaptcha#43]
Hey, thanks for publishing docs at docs.typo3.org.
We've noticed the following issues which you might want to solve:

- [ ] Rendering for 11.0.0 release failed.
- [ ] Rendering for master release failed.
- [ ] Version 10.0.0 didn't trigger any rendering yet. See https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocForExtension/ReregisterVersions.html about how to re trigger a version.

 We've moved the rendering from Bamboo to GitHub Actions. That's the reason I can't provide the logs of failed rendering. You might want to try out the local rendering via Docker to find related issues. You could also use `documentation-draft` branch, as documented: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocForExtension/Webhook.html#how-webhooks-work

You can comment on that issue to get further info or notify myself if everything is working.
We will set up corresponding redirects once everything is working.

**Comment by garbast** [comment]
Thanks for bringing this up. For the main and develop branch the documentation is fixed now. So upcoming releases will render correctly.
