### ISSUE TITLE
Firewall problems with file_get_contents

### ISSUE THREAD

**Issue by yvirtp** [evoWeb/recaptcha#47]
Hey there, we have found out, that on our shared hosting there is a problem with the file_get_contents call.
Since it doesn't resolve via the Proxy we end up getting a timed out message from the google api.

We tested to call the api with the TYPO3 RequestFactory and it resolved the Proxy correctly.
Since we are using this extension we would be happy if we can find a solution for this behaviour.

Best Regards

Yannis Viol

**Comment by garbast** [comment]
If you are able, please provide a pull request, to solve the problem i a timly maner.

**Comment by yvirtp** [comment]
I added a new pull request and its ready to get checked

**Comment by agendartobias** [comment]
Hello, i can confirm this problem on our TYPO3 instance to. @yvirtp i tried your fix and it works, thank you so much. I hope it get merged.
