### ISSUE TITLE
Load ViewHelper by index (e.g., timestamp)

### ISSUE THREAD

**Issue by Barakur** [evoWeb/recaptcha#49]
### Current behavior

The View Model isn't loaded with other form element extensions 

### Expected behavior/output

The ViewModel is always loaded

### Steps to reproduce

Install another extension with a custom form element that loads its ViewModel without index, e.g., https://extensions.typo3.org/extension/form_country_select or https://extensions.typo3.org/extension/form_element_linked_checkbox

### Environment

- Form Country Select version(s): 1.4.1
- TYPO3 version(s): 10.4.26
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: XUbuntu

### Possible Solution

Change
```
additionalViewModelModules:
  - 'TYPO3/CMS/Recaptcha/Backend/FormEditor/RecaptchaViewModel'
```

to

```
additionalViewModelModules:
  1647849522: 'TYPO3/CMS/Recaptcha/Backend/FormEditor/RecaptchaViewModel'

```

**Important**: Use a unique timestamp to prevent conflicts with other extensions.  
Also don't do this inside a Yaml file that is imported by `imports`. It seems Symfony has a Bug because the Indexes get removed again. It has to be done in the main Yaml file imported by TypoScript.

### Additional context

By adding the ViewModel without an index it gets added at index 0. Problem is, this is true for every other extension that adds ViewModels like this. This results in only a single ViewModel to be loaded, either the first or last extension (this I didn't check).

**Comment by Barakur** [comment]
What is the status of this issue? It creates conflicts with other extensions that add form elements.

**Comment by garbast** [comment]
Feel free to submit a pull request to speed things up.
