### ISSUE TITLE
Parameters in ext_conf_template.txt are not used

### ISSUE THREAD

**Issue by dogawaf** [evoWeb/recaptcha#5]
Hello

In CaptchaService, the configuration is first loaded from ext_conf_template.txt, and the overriden with typoscript setup.
If an integrator (like me) tried to redefine something in the extension configuration, it will be always overriden with typoscript setup.

Maybe we should have only one way to setup the extension: TS or ext_conf_template.txt.

What do you think?

Cheers

**Comment by garbast** [comment]
Purpose of ext_conf_template.txt is to have some solid fallback value for uses like in backend login captcha. If you dont want ot have the settings overriden by TypoScript just dont include the static include but add only those settings that you need in your own typoscript.

Both setup possibilities are needed and do not need to be redefined.

**Comment by dogawaf** [comment]
Okay. The docs is pretty clear about that: 

> For all frontend usage of the recaptcha service the backend settings are taken and then overridden with TypoScript. But setting the backend portion is optional. If these are empty the TypoScript configuration is mandatory.

Please apologize for taking your time.
