### ISSUE TITLE
Captcha always showing "testing purposes only"

### ISSUE THREAD

**Issue by ma8bi4ne** [evoWeb/recaptcha#53]
I added the reCaptcha.Extension to Typo3 11.5.13 and generated public and secret key with Google.
I added them in the extension configuration, flushed all caches, added the captcha to my form and still get this error message.
Any ideas on how to avoid it and get the captcha going?

**Comment by johollmann** [comment]
> I added the reCaptcha.Extension to Typo3 11.5.13 and generated public and secret key with Google. I added them in the extension configuration, flushed all caches, added the captcha to my form and still get this error message. Any ideas on how to avoid it and get the captcha going?

had the same issue. There are two places where you can configure the private/public key's. First is in the extension settings (which did'nt work for me either) and the other one is in typoscript constants. And that one works for me.
