### ISSUE TITLE
requestFactory->createRequest doesn't work

### ISSUE THREAD

**Issue by internetgalerie-github** [evoWeb/recaptcha#61]
Hello,
Using the reCAPTCHA extension in EXT:form-Forms gives an error on sending the form.
Line 215 in Classes/Service/CaptchaService.php:
got changed for V12 to the following:
$response = $this->requestFactory->createRequest($this->configuration['verify_server'] . '?' . $params, 'POST');

But this doesn't work. First of all, the method takes the method as first parameter and the URI as the second, and doesn't return a response Object.

Changing it back to:
$response = $this->requestFactory->request($this->configuration['verify_server'] . '?' . $params, 'POST');

Fixes the issue.

**Comment by RTPAst** [comment]
We have the same problem and have created a pull request.

**Comment by garbast** [comment]
after comparing core RequestFactory in 11 and 12 i reverted the change as suggestes back to $this->requestFactory->request

**Comment by garbast** [comment]
Fixed with commit eca0b3efaeb54b7ca28f07e8a0ee89c33a460d95
