### ISSUE TITLE
set `excludeFromConcatenation` by default

### ISSUE THREAD

**Issue by mikestreety** [evoWeb/recaptcha#64]
Hey, thanks for such a helpful extension 👍 

I recently came across an issue where `compressed` JS assets are being created on every page request (which can quickly fill a server up).

With thanks to Lukas ([on the TYPO3 Slack](https://typo3.slack.com/archives/C025BQLFA/p1691346100868939)) it was identified as the Google JS included with this extension being the issue - it seems to request the JS each page load.

Is is possible to include `excludeFromConcatenation` as a default? If you're happy for it to be added it I can make a merge request

```
page.includeJSFooterlibs.recaptcha.excludeFromConcatenation = 1
```

Thanks again

**Comment by garbast** [comment]
A PR would be nice. Thanks in advanced.

**Comment by mikestreety** [comment]
Sorry for the spam of PRs but thought it would be good to update all versions 👍

**Comment by garbast** [comment]
Non LTS versions do not get any release. Sorry.
