### ISSUE TITLE
Development mode active. Do not expect the captcha to appear 

### ISSUE THREAD

**Issue by dr2okevin** [evoWeb/recaptcha#71]
Using the Captcha with the TYPO3 Form editor shows in frontend always the message "reCAPTCHA
Development mode active. Do not expect the captcha to appear ".
Application Context is "Production". Keys are set in extension Settings. I also tried as a quick fix to check the option "plugin.recaptcha.enforceCaptcha". But no luck.

TYPO3 11.5.30
evoweb/recaptcha 11.0.4

**Comment by garbast** [comment]
The Captcha is shown if 
(typoscript robotMode = 0) and (request is a backend request or the context is not development or enforceCaptcha = true)

You need to check if your config matches this requirements.

The extension works on other installation, so there must be something with your setup.

**Comment by dr2okevin** [comment]
As I had already written, the context is production. robot mode is also not active.
![grafik](https://github.com/evoWeb/recaptcha/assets/1845792/f7902aa2-1017-41b5-b18b-4dc371525ec1)
![grafik](https://github.com/evoWeb/recaptcha/assets/1845792/f84bc8f4-67fc-4a9d-9105-6004f8fb101c)

**Comment by pmarkus84** [comment]
I have the same problem with Typo3 12.4.22.

**Comment by garbast** [comment]
I checked the recaptcha functionality on TYPO3 12.4.23 with version 13.1.1 and checked the following situations:

- set Development context
- add recapcha field to form
- no TypoScript at all
-> Development mode active. Do not expect the captcha to appear

- add TypoScript include static
- set the constant enforceCaptcha to 1
-> recpatcha rendered

- remove constants enforceCaptcha
- set Production context
-> recaptcha rendered

So from what i tested, it is working as intended. Check the steps above if your installation is configured correctly.

**Comment by pmarkus84** [comment]
Version 13.1.1 works for me. Version 14.0.0 has this problem. Thanks for your try.

**Comment by garbast** [comment]
I checked the same on TYPO 13.4.1 with recaptcha 14.0.0 and removing enforceCaptcha and setting the context to Production showed the captcha.

IMPORTANT Do not use 14.0.0 on TYPO3 12. It was mistakenly configured to be installable in TYPO3 12. The tag is now deleted from the repository and packagist.
