### ISSUE TITLE
Typo3 v12 reports Error with view-model.js

### ISSUE THREAD

**Issue by mrwhy-orig** [evoWeb/recaptcha#75]
I'd like to use this extension, but atm I'm stuck with an error. 
If I want to edit an existing Form or create a new one, I get an inifinte spinner without any shown errors. The console displays the following error: 

Uncaught (in promise) Error: Unable to resolve specifier '@evoweb/recaptcha/backend/form-editor/view-model.js' imported from (https://testing.local/typo3/module/web/FormFormbuilder/FormEditor/index?token=32c0c11a69a5cd2b701b00da7d53275a7a7b569c&formPersistenceIdentifier=1:/form_definitions/allgemeinesKontaktformular.form.yaml)

I'm using the latest release of this extension from the ter with Typo3 v 12.4.1

**Comment by garbast** [comment]
Im using TYPO3 12.4.7 with recaptcha 12.0.1 and it works as expected both with existing and new forms.

**Comment by mrwhy-orig** [comment]
Right. So I figured this extension isn't compatible until 12.4.5 There was a bug in previous releases regarding ESM.
