### ISSUE TITLE
reCaptcha always in english

### ISSUE THREAD

**Issue by webian** [evoWeb/recaptcha#8]
I'm not sure if I'm missing something but the reCaptcha is always displayed in english no matter what value I set for `lang` constant.
It also fails to auto-detect language if I leave `lang` constant empty.

TYPO3 8.7
reCAPTCHA 8.2.0

**Comment by webian** [comment]
This is the generated code by the viewhelper:
`<div class="g-recaptcha" data-sitekey="6LcSPSITAAAAAAqs1YcdZ2gMB84spxvsNB8_lLJ_"></div>`

But the resulting iframe has `hl=en` embedded in the src:
`https://www.google.com/recaptcha/api2/anchor?k=6LcSPSITAAAAAAqs1YcdZ2gMB84spxvsNB8_lLJ_&co=aHR0cDovL2wub3pvbmVrYXlhay5jb206ODA.&hl=en&v=v1515997865826&size=normal&cb=2v0mpe7b9zuj`

**Comment by garbast** [comment]
reCaptcha always takes the browser language into account. So if there is an hl=en in the iframe Url its not because of the extension but taken from your browser. Your could try to add hl=de to the api url in TypoScript constants

plugin.tx_recaptcha.api_server = https://www.google.com/recaptcha/api.js?hl=de

But in general i would suggest to not override it and leave it to the browser to choose what language to display.

**Comment by Ich5003** [comment]
Heya,

I have exactly the same problem.
Setting the lang contstant to anything or leaving it empty doesn't work. ?hl=en is always added.
Only adding it to api.js changes the language.

Tried with multiple browsers. Please recheck!

Lucas

**Comment by garbast** [comment]
As written above the lang constant does not get used. You need to modify the api_server constant to change the url for different ?hl= values

**Comment by Ich5003** [comment]
That works.
Still I think this `reCaptcha always takes the browser language into account.` is wrong.

**Comment by garbast** [comment]
Please take a closer look at the hl configuration in the documentation of googles recaptcha ( https://developers.google.com/recaptcha/docs/display#config ). There it states clearly:

**Optional. Forces the widget to render in a specific language. Auto-detects the user's language if unspecified.**
