### ISSUE TITLE
Google Captcha not working in TYPO3 v12

### ISSUE THREAD

**Issue by Denneee** [evoWeb/recaptcha#81]
Hello,
I installed the extension accordingly to the users manual and setted the correct public and private keys.

I integrated the captcha in to a form from EXT:Form and when I open the website i get a captcha error that is telling me
"Website: Key type invalid"

I tried v2 and v3 keys but still the same error message.

I use TYPO3 v12 with php 8.2

**Comment by garbast** [comment]
key type invalid only appears if something is wrongly configured in google cloud console. There is no error in the extension but on google side. Nothing i can do about.
