### ISSUE TITLE
trim(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by ayacoo** [evoWeb/recaptcha#84]
**Error message:**

```
PHP Runtime Deprecation Notice: trim(): Passing null to parameter #1 ($string) of type string is deprecated 
in /var/www/html/vendor/evoweb/recaptcha/Classes/Validation/RecaptchaValidator.php line 35
```

**Versions**

- TYPO3 11.5
- recaptcha 11.0.4
- PHP 8.2

**Context**

- Dev mode is enabled = no recaptcha is visible
- Already fixed in v12 and v13

**Solution**

https://github.com/evoWeb/recaptcha/blob/11.0.4/Classes/Validation/RecaptchaValidator.php#L35

$value = trim(GeneralUtility::_GP('g-recaptcha-response'));
to 
$value = trim(GeneralUtility::_GP('g-recaptcha-response') ?? '');

**Comment by ayacoo** [comment]
@garbast Are you planning a TER release for it or should I just continue to use the 11x branch for it?

**Comment by garbast** [comment]
Version 11.0.6 with this fix just got released
