### ISSUE TITLE
compatibility cms-core doesn't align with TER compatibility

### ISSUE THREAD

**Issue by AquaTixzzZ** [evoWeb/recaptcha#88]
If you look at the v14 and v13 tags in github. It says in the composer.json that it could either use core ^12.4 or ^13.0
if we look in the TYPO3 TER it says v14 and v13 only are compatible with cms-core ^13.0.

Either the TER supported version(s) seems wrong with v13 and v14 and should say **works with 12.0.0- 13.0.0**

or the composer.json needs to be changed because : 
```
require { 
"typo3/cms-core": "^12.4" || 

}
```
isnt'valid anymore in the composer.json.

**Comment by garbast** [comment]
Thanks for making aware. Version 14.0.1 is limited to only 13.x because since the implementation of the siteSet the replacement of constants does not work in 12.4 anymore.

Resolved by 2e7d0729b57a136dab24f8131d73185c32e8226d
