### ISSUE TITLE
Invisible Recaptcha not functioning on form with summary page

### ISSUE THREAD

**Issue by aglahir1** [evoWeb/recaptcha#90]
In a form that has several pages (steps) the recaptcha must be on the final page because the submit button calls the javascript that fills the hidden field. This much is clear.

In a form with a summary page, the summary page is usually the last page, however on a summary page you cannot place any fields.

Therefore if you have a summary page in a form you cannot use the invisible recaptcha.

The only workaround I've found is to add another step after the summary just for the recaptcha field, this is not good though, because after a summary page many people assume that was all. And even if they don't an empty page with just a submit button is not great.

~~It would be good if the javascript for the hidden recaptcha field was placed on the submit button of the page that contains the recaptcha field.~~
Edit: this probably wouldn't work because too much time would elapse between the JS call and the PHP validation.

**Comment by garbast** [comment]
I see your point, but the case is so few, that will not work on it without sponsorship.

But you are welcome to provide a PR that fixes the problem.

**Comment by garbast** [comment]
Please reopen once you have a PR ready.
